### ISSUE TITLE
Add a new dataset & benchmark

### ISSUE THREAD

**Issue by junhongmit** [alexfanjn/Graph-Neural-Networks-With-Heterophily#5]
Hi alexfanjn,

Thanks for this comprehensive collection of works! I would like to add this interesting work that provide new datasets and new GNN on heterophilic and heterogeneous graph:

When Heterophily Meets Heterogeneity: New Graph Benchmarks and Effective Methods (https://arxiv.org/abs/2407.10916)
The open-source GitHub repository can be found at https://github.com/junhongmit/H2GB.

Thanks very much!

Best,
Junhong

**Comment by alexfanjn** [comment]
Added, thank you so much!
